services:
  # proxy:
  #   image: traefik:3.0
  #   volumes:
  #     - ${XDG_RUNTIME_DIR}/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
  #   # userns_mode: "keep-id"
  #   ports:
  #     - "80:80"
  #     - "8090:8080"
  #   command:
  #     - --providers.docker=true
  #     - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
  #     - --providers.docker.exposedbydefault=false
  #     - --entrypoints.http.address=:80
  #     - --entrypoints.https.address=:443
  #     - --accesslog
  #     - --log
  #     - --log.level=DEBUG
  #     - --api
  #     - --api.insecure=true
  #     - --providers.docker.endpoint=unix:///run/user/1000/podman/podman.sock
  #   labels:
  #     - traefik.enable=true
  #     - traefik.constraint-label=traefik-public
  #     # - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
  #   networks:
  #     - traefik-public

  backend:
    restart: "no"
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=local
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    image: node:20-slim
    restart: "no"
    command: sh -c "corepack enable && pnpm install && pnpm dev --host"
    build:
      context: ./frontend
      args:
        - PUBLIC_BACKEND_API_URL=http://backend:8000/api/v1
        - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.svelte-kit
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api/v1
      - NO_PROXY=localhost,127.0.0.1,backend
    working_dir: /app

  adminer:
    restart: "no"
    ports:
      - "8081:8080"

  db:
    restart: "no"
    ports:
      - "5432:5432"

  db-test:
    image: postgres:18.1
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - test-app-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d apartments -U apartments" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  test-app-db-data:
    
networks:
  traefik-public:
    external: false
