services:
  db:
    image: postgres:18.1
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d apartmentsdb -U apartmentsdb" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  prestart:
    image: apartments-backend:latest
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart.sh
    environment:
      - PROJECT_NAME=Apartments
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  backend:
    image: apartments-backend:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - PROJECT_NAME=Apartments
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD? Variable not set}
      - KLEINANZEIGEN_USERNAME=${KLEINANZEIGEN_USERNAME?Variable not set}
      - KLEINANZEIGEN_PASSWORD=${KLEINANZEIGEN_PASSWORD?Variable not set}
      - ENVIRONMENT=production
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: apartments-frontend:latest
    restart: always
    environment:
      - PUBLIC_BACKEND_API_URL=${PUBLIC_BACKEND_API_URL}
    build:
      context: ./frontend
      args:
        - PUBLIC_BACKEND_API_URL=https://${PUBLIC_BACKEND_API_URL?Variable not set}
        - NODE_ENV=production



volumes:
  app-db-data:
