apiVersion: 1
datasources:
  - name: PostgresDB
    type: postgres
    access: proxy
    url: ${DB_HOST}:5432
    database: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    isDefault: true
    jsonData:
      sslmode: disable
